# Generated by Django 5.2 on 2025-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_notas_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota3',
            field=models.FloatField(),
        ),
    ]
